Rename model's name and and add some description
ietf-ccamp-wg/ietf-network-inventory pull request #67
Opened 2023-02-01 08:49 UTC by YuChaode

1. rename the data model and limit it to hardware scope;
2. add some more description to fix the issue mentioned by tom petch;
3. remove rack-number in rack, firmware-rev in NE;
4. add relative-position of chassis in rack;
5. remove equipment room, rack, NE's info in the component's parent reference structure.

2023-02-16 12:12 UTC, italobusi commented
**[2023-02-15 Network Inventory weekly call](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2023-02-15.md)**

The root container has to be renamed as "network-hardware-inventory" based on the clarified scope of the document

After that change, the draft PR would be ready for review

- [ ] @YuChaode update the root container and start the PR review

- [ ] @aguoietf @sergiobelotti @jbouqui153 review the PR once ready for review

2023-02-28 14:47 UTC, jbouqui153 commented on ietf-network-hardware-inventory.yang
> -        "The vendor-specific firmware revision string for the NE.";
Firmware does not really apply to the NE but more to the boards, pluggables etc inside an NE

2023-02-28 14:50 UTC, jbouqui153 commented on ietf-network-hardware-inventory.yang
> +      "Attributes applis for rack only.";
applicable

2023-02-28 14:55 UTC, jbouqui153 commented on ietf-network-hardware-inventory.yang
> -        "An integer identifier of rack.";
An integer identifier of the rack

2023-02-28 14:56 UTC, jbouqui153 commented on ietf-network-hardware-inventory.yang
> +        "Location information of rack, this location infomation is
Location information of the rack

2023-02-28 14:58 UTC, jbouqui153 commented on ietf-network-hardware-inventory.yang
> -    }
height, width, depth, max-voltage should be optional in my opinion

2023-02-28 15:00 UTC, jbouqui153 commented on ietf-network-hardware-inventory.yang
> +            "An indication of the relative posistion of this child
position

2023-02-28 15:01 UTC, jbouqui153 commented on ietf-network-hardware-inventory.yang
>              "The child components' identifier that are physically
uncomplete sentence

2023-02-28 15:58 UTC, aguoietf commented on ietf-network-hardware-inventory.yang
> +      "https://www.iana.org/assignments/yang-parameters";
Maybe I missed something, but I wonder why we put a link instead of RFC8348 which defines the module

2023-02-28 16:01 UTC, aguoietf commented on ietf-network-hardware-inventory.yang
> +      "Attributes applicable for network element";
applicable for --> applicable to

2023-02-28 16:09 UTC, aguoietf commented on ietf-network-hardware-inventory.yang
> -        "The vendor-specific firmware revision string for the NE.";
I think this change actually removes the firmware-rev from the NE, so it aligns with your comment.

2023-02-28 16:16 UTC, aguoietf commented on ietf-network-hardware-inventory.yang
> +        "Location information of rack, this location infomation is
The location information of the rack, which comprises the name of the equipment room, row number, and column number.

2023-02-28 16:16 UTC, aguoietf commented on ietf-network-hardware-inventory.yang
> -        "An integer identifier of rack.";
rack-number is being removed, I think.

2023-02-28 16:18 UTC, aguoietf commented on ietf-network-hardware-inventory.yang
> +        "Height of rack.";
Rack height

2023-02-28 16:18 UTC, aguoietf commented on ietf-network-hardware-inventory.yang
> +        "Width of rack.";
Rack width

2023-02-28 16:18 UTC, aguoietf commented on ietf-network-hardware-inventory.yang
> +        "Depth of rack.";
Rack depth

2023-02-28 16:21 UTC, aguoietf commented on ietf-network-hardware-inventory.yang
>              "The child components' identifier that are physically
The identifier of the child component physically contained by this component.

2023-02-28 16:24 UTC, aguoietf commented on ietf-network-hardware-inventory.yang
> +            "Identifier of this component's hierarchial parent
A list of identifiers to all hierarchical parents of this component

2023-02-28 16:27 UTC, jbouqui153 commented on ietf-network-hardware-inventory.yang
> +      "Some attributes belong to chassis only.";
Specific attributes applicable to chassis only

2023-02-28 16:28 UTC, jbouqui153 commented on ietf-network-hardware-inventory.yang
> +      "Some attributes belong to slot only.";
Specific attributes applicable to slot only

2023-02-28 16:28 UTC, jbouqui153 commented on ietf-network-hardware-inventory.yang
> +      "Some attributes belong to board only.";
Specific attributes applicable to board only

2023-02-28 16:29 UTC, jbouqui153 commented on ietf-network-hardware-inventory.yang
> +      "Some attributes belong to port only.";
Specific attributes applicable to port only

2023-02-28 16:29 UTC, aguoietf commented on ietf-network-hardware-inventory.yang
> +              0-index.";
This list shows the identifiers of this component’s parents in a hierarchy. The index parameter defines the hierarchy: the top parent has an index of 0.

2023-02-28 16:31 UTC, aguoietf commented on ietf-network-hardware-inventory.yang
> +                should be of low index value. The index start from 0.";
The index shows the order of this component’s parents in a hierarchy. The top parent has a low index value. The index starts from 0.

2023-02-28 16:32 UTC, aguoietf commented on ietf-network-hardware-inventory.yang
> +        "This extension differs with different component class.";
This extension differs between different component classes

2023-02-28 16:33 UTC, aguoietf commented on ietf-network-hardware-inventory.yang
> +      "Some attributes belong to slot only.";
Slot-specific attributes

2023-02-28 16:33 UTC, aguoietf commented on ietf-network-hardware-inventory.yang
> +      "Some attributes belong to board only.";
Board-specific attributes

2023-02-28 16:33 UTC, aguoietf commented on ietf-network-hardware-inventory.yang
> +      "Some attributes belong to port only.";
Port-specific attributes

2023-02-28 16:34 UTC, aguoietf requested changes
Please see the comments -

2023-02-28 16:34 UTC, sergiobelotti commented on ietf-network-hardware-inventory.yang
> +      "https://www.iana.org/assignments/yang-parameters";
Same comment

2023-02-28 16:36 UTC, sergiobelotti commented on ietf-network-hardware-inventory.yang
> +      "Attributes applicable for network element";
agree

2023-02-28 16:37 UTC, sergiobelotti commented on ietf-network-hardware-inventory.yang
> -        "The vendor-specific firmware revision string for the NE.";
Correct, the change is exactly to remove firmware-rev attribute

2023-02-28 16:49 UTC, sergiobelotti commented on ietf-network-hardware-inventory.yang
> +      "Attributes applis for rack only.";
agree

2023-02-28 16:51 UTC, sergiobelotti commented on ietf-network-hardware-inventory.yang
> +        "Location information of rack, this location infomation is
Location information of rack or this location information is related to rack

2023-02-28 16:54 UTC, sergiobelotti commented on ietf-network-hardware-inventory.yang
> +        "Location information of rack, this location infomation is
Agree on the proposal

2023-02-28 16:55 UTC, sergiobelotti commented on ietf-network-hardware-inventory.yang
> -        "An integer identifier of rack.";
Yes, rack number is removed

2023-02-28 16:58 UTC, sergiobelotti commented on ietf-network-hardware-inventory.yang
> +        "Height of rack.";
If I'm not wrong there was comment from Fabio that these attributes related to rack should not be exposed by the controller

2023-02-28 16:59 UTC, sergiobelotti commented on ietf-network-hardware-inventory.yang
> +        "Width of rack.";
same comment as above

2023-02-28 16:59 UTC, sergiobelotti commented on ietf-network-hardware-inventory.yang
> +        "Depth of rack.";
same as above

2023-02-28 17:00 UTC, sergiobelotti commented on ietf-network-hardware-inventory.yang
>              "The child components' identifier that are physically
> The identifier of the child component physically contained by this component.

I Agree on the description

2023-02-28 17:09 UTC, sergiobelotti commented on ietf-network-hardware-inventory.yang
> +            "An indication of the relative posistion of this child
Proposed changes: The relative position with respect the parent component

2023-02-28 17:18 UTC, sergiobelotti commented on ietf-network-hardware-inventory.yang
> +              0-index.";
I agree on the proposed modification

2023-02-28 17:23 UTC, sergiobelotti commented on ietf-network-hardware-inventory.yang
> +            }
The index parameter is used to define the hierarchy among the parents of component. The top parent has an index of 0.

2023-02-28 17:25 UTC, sergiobelotti commented on ietf-network-hardware-inventory.yang
> +                "The identifier of the hierarchial parent component.";
The identifier of the parent's component in the hierarchy.

2023-02-28 17:26 UTC, sergiobelotti commented on ietf-network-hardware-inventory.yang
> +      "Some attributes belong to chassis only.";
I agree on the proposed modification

2023-02-28 17:27 UTC, sergiobelotti commented on ietf-network-hardware-inventory.yang
> +      "Some attributes belong to port only.";
Agree

2023-03-01 15:04 UTC, italobusi approved these changes
**2023-03-01 Inventory Call**

Comments resolutions as agreed during the call

2023-03-01 15:11 UTC, italobusi commented on ietf-network-hardware-inventory.yang
> +        "Location information of rack, this location infomation is
Resolution agreed in https://github.com/ietf-ccamp-wg/ietf-network-inventory/pull/67/files#r1121813864

2023-03-01 15:11 UTC, italobusi commented on ietf-network-hardware-inventory.yang
> +        "Location information of rack, this location infomation is
Resolution agreed in https://github.com/ietf-ccamp-wg/ietf-network-inventory/pull/67/files#r1121813864

2023-03-01 15:11 UTC, italobusi commented on ietf-network-hardware-inventory.yang
> +            "An indication of the relative posistion of this child
Resolution agreed in https://github.com/ietf-ccamp-wg/ietf-network-inventory/pull/67/files#r1121831216

2023-03-01 15:11 UTC, italobusi commented on ietf-network-hardware-inventory.yang
> +            "Identifier of this component's hierarchial parent
Resolution agreed in https://github.com/ietf-ccamp-wg/ietf-network-inventory/pull/67/files#r1121849281

2023-03-01 15:11 UTC, italobusi commented on ietf-network-hardware-inventory.yang
> +              0-index.";
Resolved in https://github.com/ietf-ccamp-wg/ietf-network-inventory/pull/67/files#r1121844545

2023-03-01 15:11 UTC, italobusi commented on ietf-network-hardware-inventory.yang
> +                should be of low index value. The index start from 0.";
Resolved in https://github.com/ietf-ccamp-wg/ietf-network-inventory/pull/67/files#r1121853790

2023-03-01 15:11 UTC, italobusi commented on ietf-network-hardware-inventory.yang
> +            }
Resolved in https://github.com/ietf-ccamp-wg/ietf-network-inventory/pull/67/files#r1121853790

2023-03-01 15:11 UTC, italobusi commented on ietf-network-hardware-inventory.yang
> +      "Some attributes belong to slot only.";
Resolved in https://github.com/ietf-ccamp-wg/ietf-network-inventory/pull/67/files#r1121860726

2023-03-01 15:11 UTC, italobusi commented on ietf-network-hardware-inventory.yang
> +      "Some attributes belong to board only.";
Resolved in https://github.com/ietf-ccamp-wg/ietf-network-inventory/pull/67/files#r1121861787

2023-03-01 15:11 UTC, italobusi commented on ietf-network-hardware-inventory.yang
> +      "Some attributes belong to port only.";
Resolved in https://github.com/ietf-ccamp-wg/ietf-network-inventory/pull/67/files#r1121862842

2023-03-01 15:36 UTC, italobusi commented on ietf-network-hardware-inventory.yang
>              contained by this component.";
**2023-03-01 Inventory Call**

```suggestion
```

2023-03-02 10:39 UTC, italobusi commented on ietf-network-hardware-inventory.yang
> +                   "nhi:equipment-room/nhi:name";
```suggestion
              path "/nhi:network-hardware-inventory/" +
                   "nhi:equipment-rooms/nhi:equipment-room/nhi:name";
```

2023-03-03 21:40 UTC, aguoietf approved these changes

2023-03-06 07:57 UTC, merged